services:
  postgres:
    container_name: bsn_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_network
    volumes:
      - postgres:/var/lib/postgres
    ports:
      - "5432:5432"
    networks:
      - book_network
    restart: unless-stopped

  mail-dev:
    container_name: bsn_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - book_network

networks:
  book_network:
    driver: bridge

volumes:
  postgres:
    driver: local