spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_network
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: user
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls: true
        connectiontimeout: 5000
        timeout: 3000
        write-timeout: 5000